//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limena_surveys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int ID_cliente { get; set; }
        public string idSAP_cliente { get; set; }
        public string nomSAP_cliente { get; set; }
        public string idSAP_vendedor { get; set; }
        public string nomSAP_vendedor { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
