//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limena_surveys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_encuesta
    {
        public int ID_detalle { get; set; }
        public Nullable<int> seccion { get; set; }
        public string seccion_descripcion { get; set; }
        public string ID_item { get; set; }
        public string descripcion_item { get; set; }
        public Nullable<bool> value_item_chk { get; set; }
        public string idSAP_cliente { get; set; }
    }
}
